### ISSUE TITLE
How do I disable SafeDiscShim after installation?

### ISSUE THREAD

**Issue by elliotpotts** [RibShark/SafeDiscShim#11]
Re-running the installer seems to give no option. Preferably I'd like to temporarily disable the shim but in particular I'd like to avoid the spawning of child processes while I debug the original executable.

**Comment by RibShark** [comment]
Same as any program, you should be able to uninstall it through the Windows Control Panel->Programs and Features or through Settings->Apps->Installed Apps

**Comment by elliotpotts** [comment]
Thank you!
