### ISSUE TITLE
Confused about what SafeDiscShim actually does.

### ISSUE THREAD

**Issue by SeanRamey** [RibShark/SafeDiscShim#18]
I'm confused about this tool. What EXACTLY does it do? Does it still basically implement the complete functionality of SafeDisc copy protection, just not as some insecure driver? If so, why wasn't SafeDisc driver originally created this way?

Or does this tool just send the correct data no matter if the disc is a copy or not?

**Comment by RibShark** [comment]
Yeah that's correct. SafeDiscShim replicates the IOCTL in the last driver version 1:1; nothing it does requires kernel mode, it literally returns pre-defined responses. Earlier driver versions would have checked for debuggers and such and the responses would change depending on what it detected, but the latest driver version just hardcodes the "correct" response and returns that.

Copied discs will still be detected as this was done outside of the driver, in user-mode code that is embedded in every safedisc executable.

**Comment by SeanRamey** [comment]
Thanks for the answer!
