### ISSUE TITLE
Tried 3 different games, none works... without compatibility mode or affinity set to 1

### ISSUE THREAD

**Issue by SkullKid2000** [RibShark/SafeDiscShim#24]
Like the title says. I've tried many different things, but compatibility mode or setting affinity to 1 or 3 seems to be the only things that might get the games running. The games are 
Battlefield 1942
Robot Wars Arenas of Destruction
Manhunt

EDIT: Manhunt used SecuROM 7, so that doesn't count.

**Comment by SkullKid2000** [comment]
Got Robot Wars Arenas of Destruction to work in Windows 98 / ME compatibility mode, but Battlefield 1942 still won't run, even with Alcohol 120% emulation of the disc(s) in mds/mdf format.

**Comment by SkullKid2000** [comment]
Also, I works almost always when running games with one core, but then if I want to run them att full power, I need to open Task Manager and set affinity back to all cores.

**Comment by SkullKid2000** [comment]
I can now confirm that when dual-booting with Windows 11 and Windows 10, SafeDiscShim works fine in Windows 10 without any compatibility mode, or affinity settings. Weird... something seems broken in Windows 11...

**Comment by SkullKid2000** [comment]
When disabling Driver Signature Enforcement in Windows 11, SafeDiscShim works every time, without setting affinity OR compatibility mode... sadly I cannot give any info about it, except maybe the logs, of course-

**Comment by mirh** [comment]
Uuh, no - please. Keep this open. 
I'd really like to figure out what's going on here. 

The only things SDS installs are `drvmgt.dll` and `SafeDiscShim.sdb`. This one in turn applying the *InjectDll* shim on every "~#####.tmp" file (that is, the real executables that safedisc tries to load on execution). 
I can guess that if disabling DSE fixes the situation there's probably some security mechanism involved, but I wasn't aware of any one influencing dlls. 
Can you check the Program Telemetry logs in `Microsoft/Windows/Application-Experience` events? And try to disable [this stuff](https://sourceforge.net/p/dxwnd/discussion/general/thread/1884a3c377/#3cba)?

**Comment by SkullKid2000** [comment]
Alright mirh, I'll try what you said. I'll keep you updated.

**Comment by SkullKid2000** [comment]
Here's the Program Telemetry logs for launching Battlefield 1942.
[SafeDiscShim_log.zip](https://github.com/user-attachments/files/16530158/SafeDiscShim_log.zip)

**Comment by SkullKid2000** [comment]
I had virtualization disabled in my UEFI BIOS. So that's not the issue, but the logs will hopefully provide some info about what's going on...

**Comment by SkullKid2000** [comment]
Ultimate Solution: Disable Smart App Control by setting it to "Off".

**Comment by mirh** [comment]
https://learn.microsoft.com/en-us/windows/apps/develop/smart-app-control/overview
I see. Though maybe this could still be considered a bug, in the sense that the super proper way to fix this would be code signing.

**Comment by SkullKid2000** [comment]
Thing is if I enable Smart App Control, I suppose I cannot disable it later. So I don't think I can test it.

**Comment by mirh** [comment]
Mhh, that's not it as it complains about secdrv.sys - and it is dated to five days ago (around the time you first closed this issue).
I would hope you could find somewhere in there (or perhaps in some other log) the actual complaints about SDS.

**Comment by SkullKid2000** [comment]
I re-enabled Smart App Control from the Advanced Startup Command Prompt. I'll look into it again now.

**Comment by SkullKid2000** [comment]
Here's a log with the game Battlefield 1942 started in Evaluation Mode of Smart App Control, and now, of course,
[Log.zip](https://github.com/user-attachments/files/16542065/Log.zip)
 it won't launch.

**Comment by mirh** [comment]
That's the successful application of the sdb fix. 
I was instead more interested into some kind of log that explicitly told you "sorry but we couldn't load this library" or something...

I think you may try to create a custom view, that includes all registries and all events of the previous 10 minutes? And from there see which bucket raises a complaint.

**Comment by SkullKid2000** [comment]
Alright. I'll look again.

**Comment by SkullKid2000** [comment]
I found this when logging everything within 30 minutes.
[Log.zip](https://github.com/user-attachments/files/16550451/Log.zip)

**Comment by mirh** [comment]
Uh... It actually just seems like installer.exe calls drvmgt.dll and then crashes. Plain and simple. 
In this sense it doesn't seem like having anything to do with code signing. 

Therefore windows 98 compatibility mode is working because some of the quirks it handles are the ones that are hit here. Would it be too much for you to install the compatibility administrator tool from the windows ADK, and then check which of these individual shims can do the same?
![immagine](https://github.com/user-attachments/assets/051a8bbc-6c87-4f8a-85f8-a66ff3f9fbaa)

**Comment by SkullKid2000** [comment]
Maybe sometime I can look into that. For now, I'll disable Smart App Control, as I don't benefit from it. Also I'm suspicious by nature, so I'm not worried about getting fooled by an unsafe app.

**Comment by SkullKid2000** [comment]
Alright, I installed the Compatibility Administrator Tools (Windows 10). I'll check it now.

**Comment by SkullKid2000** [comment]
For Battlefield 1942, this shows up in the Compatibility Administrator:
![Screenshot 2024-08-10 140101](https://github.com/user-attachments/assets/f9050774-8e08-4482-badc-979accc44c19)

**Comment by mirh** [comment]
Yes, I know.. I'm saying that you try the individual shims that are forced with the win98 compatibility mode, so that we can see which of the many ones fix it. 
For starters you could like select every single ones of them, except for SingleProcAffinity and see if this one was already the solution or not.

**Comment by SkullKid2000** [comment]
Alright. Have never used this tool before, so bear with me... I'll try what you said and see what happens.

**Comment by SkullKid2000** [comment]
When disabling the SingleProcAffinity, the game won't launch, but with it enabled it works.

**Comment by mirh** [comment]
So, just to be clear.. if you enable all the other 75 shims simultaneously, nothing really change much - but with that single one then you see the difference?

**Comment by SkullKid2000** [comment]
I had about 439 shims. I don't know if we did the same thing, but the single core shim seems to be it.
![image](https://github.com/user-attachments/assets/074a09a3-7a54-4e09-a167-76d7dd6d20f0)

**Comment by mirh** [comment]
I meant, the other 75 shims that makes the win98 compatibility mode (in my screenshot).
