### ISSUE TITLE
Can't run installer on Windows 10

### ISSUE THREAD

**Issue by marifreem** [RibShark/SafeDiscShim#3]
Windows 10 Home Edition, version 22H2. OS build 19045.3930. Doesn't give me any more information than "This app can't run on your PC."

**Comment by NicknineTheEagle** [comment]
Do you have 32-bit version of Windows 10?

**Comment by RibShark** [comment]
> Do you have 32-bit version of Windows 10?

Installer should work on 32-bit systems too (I tested this).

**Comment by marifreem** [comment]
I don't use any external security software - the most I have is Windows Defender since it's been catching everything as of recent. Tried turning off any and all Windows Security protocols, but nothing has changed. Running a 64-bit version of W10.

**Comment by RibShark** [comment]
The only other thing I can suggest is that something may be corrupting the download. Try downloading it again; if it still doesn't work, reupload the setup EXE here so I can check for any corruption.
